# Generated by Django 4.0.8 on 2023-07-02 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('TermAndConditions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.container')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.userregistration')),
            ],
        ),
    ]
