# Generated by Django 4.0.8 on 2023-07-02 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_rename_status_booking_confirm_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Confirm',
            new_name='confirm',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
