# Generated by Django 4.0.8 on 2023-07-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='container',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
