# Generated by Django 4.0.8 on 2023-07-02 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_alter_booking_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='No_of',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 46, 25, 983606)),
        ),
    ]
