# Generated by Django 4.0.8 on 2023-07-03 06:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0010_booking_no_of_alter_booking_date_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='UserName',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='User',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 11, 35, 20, 857114)),
        ),
    ]
