# Generated by Django 4.0.8 on 2023-07-03 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_remove_userregistration_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 11, 44, 13, 941367)),
        ),
    ]
