# Generated by Django 4.0.8 on 2023-07-03 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0014_alter_booking_date_booked_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 1, 10, 519006)),
        ),
    ]
