# Generated by Django 4.0.8 on 2023-07-03 07:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0016_alter_booking_date_booked_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='UserDetails',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 47, 51, 591235)),
        ),
    ]
