# Generated by Django 4.0.8 on 2023-07-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0017_rename_userregistration_userdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
