# Generated by Django 4.0.8 on 2023-07-03 07:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasing', '0018_remove_userdetails_user_delete_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='')),
                ('No_of', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('TermAndConditions', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(default=datetime.datetime(2023, 7, 3, 13, 6, 5, 201869))),
                ('No_of', models.IntegerField()),
                ('confirm', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.container')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
