# Generated by Django 4.0.8 on 2023-07-03 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0020_alter_booking_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='userdetail',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leasing.userdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 14, 5, 39, 839971)),
        ),
    ]
