# Generated by Django 4.0.8 on 2023-07-03 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0021_booking_userdetail_alter_booking_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='FullName',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 15, 28, 35, 832854)),
        ),
    ]
